$global:Services = @(
    "pip-services-quotes-node"
    "pip-services-tags-node"
    "pip-services-msgtemplates-node"
    "pip-services-files-node"
    "pip-services-attachments-node"
    "pip-services-applications-node"
    "pip-services-tips-node"
    "pip-services-guides-node"
    "pip-services-help-node"
    "pip-services-imagesets-node"
    "pip-services-dashboards-node"
    "pip-facade-content-node"
)

$global:Clients = @(
    "pip-clients-quotes-node"
    "pip-clients-quotes-dotnet"
    "pip-clients-quotes-java"
    "pip-clients-quotes-go"
    "pip-clients-tags-node"
    "pip-clients-msgtemplates-node"
    "pip-clients-files-node"
    "pip-clients-attachments-node"
    "pip-clients-applications-node"
    "pip-clients-tips-node"
    "pip-clients-guides-node"
    "pip-clients-help-node"
    "pip-clients-imagesets-node"
    "pip-clients-dashboards-node"
)
